#FROM node:alpine
#WORKDIR /server
#COPY package.json ./
#COPY package-lock.json ./
#COPY ./ ./
#RUN npm install
#RUN npm run build
#CMD ["npm", "run", "start:prod"]
FROM node:16
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 5000
CMD ["npm", "run", "start"]